### ISSUE TITLE
borders of table

### ISSUE THREAD

**Issue by joomlaA1** [wenzhixin/bootstrap-table#1609]
Hi wen

I have this (a bootstrap table):
![normal](https://cloud.githubusercontent.com/assets/13029902/10776806/d1eb032c-7d4f-11e5-80d1-672a4608a2cb.png)

I want it to become like this (
    - a table with outside border only
    - no middle borders
    - padded cell or padded row?(I want a thick row)
):
![smooth](https://cloud.githubusercontent.com/assets/13029902/10776808/d2b0ad20-7d4f-11e5-9817-3aaf4f6044c9.png)

How? Thanks

**Comment by wenzhixin** [comment]
You can custom use css: http://jsfiddle.net/e3nk137y/3452/

**Comment by joomlaA1** [comment]
Thanks

but iz ugly?
![broken border](https://cloud.githubusercontent.com/assets/13029902/10782266/b488264a-7d89-11e5-8ff6-eb258f160511.png)

broken border?

**Comment by joomlaA1** [comment]
please help me.. help wanted

thanks

**Comment by joomlaA1** [comment]
@dabros hi do you have idea? thanks

**Comment by dabros** [comment]
@joomlaA1 - was fixing other issue as you posted, took 2 sec to hit F12, inspect elements, find where borders were coming from, and disable one

http://jsfiddle.net/dabros/bdwe26ag/

I just disabled one border as example, but just play with that or another fiddle, very simple.

**NOTE** just saw this no diff from @wenzhixin fiddle, which for me shows no gap - meaning its prob just you or your browser.

If those fiddle both appear with these gaps, share your browser details and ideally your exact css

**Comment by joomlaA1** [comment]
hey thanks

the wenzhixin fiddle is with gaps

@dabros your fiddle is without gaps

thanks!

**Comment by joomlaA1** [comment]
hey how about thick row?
is it padding... i tried did not work on the fiddle?

thanks

@wenzhixin @dabros

**Comment by dabros** [comment]
@joomlaA1 - you need to be clearer in what you mean, also maybe share your efforts by updating or forking jsfiddle

**Comment by joomlaA1** [comment]
like turning this (a bootstrap table):
![normal](https://cloud.githubusercontent.com/assets/13029902/10776806/d1eb032c-7d4f-11e5-80d1-672a4608a2cb.png)

to this (padded cell or padded row? I want a thick row ):
![smooth](https://cloud.githubusercontent.com/assets/13029902/10776808/d2b0ad20-7d4f-11e5-9817-3aaf4f6044c9.png)

thanks

**Comment by dabros** [comment]
@joomlaA1 - keep in mind http://getbootstrap.com/css/#tables and how that is the css core its built on, but nothing there about **taller/higher** rows or cells with **extra padding**

And again, you gotta use F12 and inspect the html being produced, which would then let you see this rule being applied to all td

https://rawgit.com/wenzhixin/bootstrap-table/master/src/bootstrap-table.css
```css
.bootstrap-table .table:not(.table-condensed), .bootstrap-table .table:not(.table-condensed) > tbody > tr > th, .bootstrap-table .table:not(.table-condensed) > tfoot > tr > th, .bootstrap-table .table:not(.table-condensed) > thead > tr > td, .bootstrap-table .table:not(.table-condensed) > tbody > tr > td, .bootstrap-table .table:not(.table-condensed) > tfoot > tr > td {
    padding: 8px !important;
}
```

So you need an '!important' of your own else it will be overwritten, and changing or overwritting that might lead to other styles youd want to overwrite too, but just use same approach. 

In this case i use '14px', and applying in my own rule doesnt break tr height like modded the original rule (with all its various selectors) did.

http://jsfiddle.net/dabros/bdwe26ag/5/

I created and applied another class that overwrites those rules, just ensure greater specificity in selectors and/or include it below bootstrap-table.css to ensure they apply, as you would in any case.
