### ISSUE TITLE
a 'table-no-bordered' with a 'hidden' column show unwanted horizontal scrollbar

### ISSUE THREAD

**Issue by gwjwin** [wenzhixin/bootstrap-table#1936]
Hi, I am using this (http://issues.wenzhixin.net.cn/bootstrap-table/index.html#issues/463.html) method to search invisible columns, but if I set the table as 'table-no-bordered', the 'No matching records found' shows with unwanted horizontal scrollbar.

Here is the example:
https://jsfiddle.net/gwjwin/gt0Ladad/1/

**Comment by dabros** [comment]
The issue appears to be this rule:

```css
.bootstrap-table .table.table-no-bordered > thead > tr > th, .bootstrap-table .table.table-no-bordered > tbody > tr > td {
    border-right: 2px solid transparent;
}
```

There is no matching rule when not `.table-no-bordered`.

Im guessing that it was made to simulate padding or something that is now no longer present in standard layout.
