### ISSUE TITLE
Feature Request: data-checkbox="true" to honor data-valign="middle"

### ISSUE THREAD

**Issue by xclntdesign** [wenzhixin/bootstrap-table#2195]
Using this as a workaround for now.

```javascript
$table.on('post-body.bs.table', function (e, data){
	$('td.bs-checkbox').each(function(evt) {
		var cell_height = $(this).height();
		var input_height = $(this).children('input').height();
		$(this).css('padding-top',((cell_height - input_height)/2)+'px');
	});
});
```

**Comment by djhvscf** [comment]
Looks good

**Comment by Psihobolt** [comment]
I'm using css
```css
.table > thead > tr > th.bs-checkbox,
.table > tbody > tr > th.bs-checkbox,
.table > tfoot > tr > th.bs-checkbox,
.table > thead > tr > td.bs-checkbox,
.table > tbody > tr > td.bs-checkbox,
.table > tfoot > tr > td.bs-checkbox {
     vertical-align : middle;
} 
```
