### ISSUE TITLE
css pollute

### ISSUE THREAD

**Issue by lxjwlt** [wenzhixin/bootstrap-table#2208]
I think 
```css
.pull-right .dropdown-menu {
    right: 0;
    left: auto;
}
```
should be 

```css
.bootstrap-table .pull-right .dropdown-menu {
    right: 0;
    left: auto;
}
```

it overrides CSS styles outside the bootstrap-table and cause some problem in my project
