### ISSUE TITLE
height 选项设置为 100% 无效

### ISSUE THREAD

**Issue by hyjiacan** [wenzhixin/bootstrap-table#3006]
bootstrapTable： v1.11.1
jQuery: 1.12.4
Browser： Google Chrome 50.0.2661.87 m

你好，我想让表头固定，从 #2837 看到需要设置表格高度，我尝试写数值是OK的，但是，表格的高度并不是固定的，而是随着页面和其它控件大小变化的，我给table加了容器，这个容器的高度是弹性的，现在想直接给表格设置属性 `height: '100%'`，但发现这样写没有效果，请问这样的写法支持不？如果还不支持，以后会支持不？

我的页面布局：

```html
<div id="container">
	<div id="toolbar">
	</div>
	<div id="table-wrapper">
		<table id="table"></table>
	</div>
</div>
```

```less
#container{
	position: relative;
	height:100%;
	padding-top:40px;
	box-sizing: border-box;
	
	#toolbar{
		position: absolute;
		width:100%;
		height:40px;
	}
	
	#table-wrapper{
		height:100%;
	}
}
```

然后我初始化的时候，写高度为 100%:

```javascript
$('#table').bootstrapTable({
	height: '100%'
});
```

这样写了，表头不会固定。

多谢 ！！
