### ISSUE TITLE
when hover in last tr, it resize table

### ISSUE THREAD

**Issue by vingorius** [wenzhixin/bootstrap-table#3178]
First please run below jsfiddle.

When hover image column, there's no problem, but hover in last row(5th row), it make scroll bar & show image partial.

How to make image not hiding ?

I adjusted z-index, but not work.

http://jsfiddle.net/vingorius/e3nk137y/14029/

**Comment by djhvscf** [comment]
This is not an issue. Here is an example with what you want: http://jsfiddle.net/djhvscf/e3nk137y/14134/

I just comment out the overflow-x, overflow-y

``` css
.fixed-table-body {
    /* overflow-x: auto; */
    /* overflow-y: auto; */
    height: 100%;
}
```
