### ISSUE TITLE
some nice CSS

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/bootstrap-table#366]
Hi
 
Here is some nice CSS for your Table:
 
```css
.fixed-table-header {
    background-color: SandyBrown ;
    color: Ivory;
}
 
.fixed-table-container tbody td {
    background-color: LemonChiffon;
}
 
.fixed-table-container tbody .selected td {
    background-color: khaki;
}
 
.fixed-table-container tbody tr:hover td {
    background-color: PeachPuff;
    cursor: pointer;
}
```

--- Rick Jordan
