### ISSUE TITLE
Enable CSS transitions for showLoading/hideLoading

### ISSUE THREAD

**Issue by cocowalla** [wenzhixin/bootstrap-table#5295]
**Description**  
When loading data, a loading template is displayed, which currently works by toggling the CSS `display` property from `none`/`flex`.

I'd like to use CSS transitions with the loading template, such as `ease-in-out`, which would make the appearance of the loading template seem "smoother". However, CSS transitions don't work with the `display` property

As an alternative, the CSS `visibility` and `opacity` properties can be used instead, for example:

```css
.fixed-table-loading {
    display: flex;
    transition: visibility 0s, opacity 0.15s ease-in-out;
    opacity: 0;
    visibility: hidden;
}

.fixed-table-loading.open {
    visibility: visible;
    opacity: 1;
}
```

The idea here is that instead of toggling a single CSS property on the element, you toggle the `open` class on the element. This approach also makes it easier for end-users to customise further, as they can simply override the `open` class with their own CSS (customisation is actually difficult now, since a CSS property is set on the element itself).

This is actually pretty straightforward to achieve, even moreso since `loadingTemplate` made it's debut in #5003 - I really appreciate this library, and I'm happy to contribute with a PR for this, if you want it?
