### ISSUE TITLE
bootstrap-table CSS is changing core BS5 modal button styles

### ISSUE THREAD

**Issue by pchaganti** [wenzhixin/bootstrap-table#5745]
**Bootstraptable version(s) affected**:
1.18.3

**Description**  
If you use BS5 in your project along with BST, the css below is resetting background color for buttons in any BS5 modal. So if you try to set a btn-primary or any other style, it will not be displayed as the bg-color is being changed to white.

```css
.modal .btn {
   border-radius: 4px;
   background-color: #fff;
   border: 1px solid #ccc;
   padding: 6px 12px;
   outline: 0;
   cursor: pointer;
}
```
