### ISSUE TITLE
Add a helper class for borderless tables

### ISSUE THREAD

**Issue by Muzical84** [wenzhixin/bootstrap-table#649]
I have a table that I don't want to have any kind of border whatsoever.  The best I can do is get rid of all of the borders except for the outermost one:
![capture](https://cloud.githubusercontent.com/assets/775601/6808695/790fd606-d223-11e4-9550-fce7538bb951.PNG)

Site CSS:
```css
#tableNameID, .borderlessTable{border-width:0!important;border-spacing:0!important;border-collapse:collapse!important;border-style:none!important;border-color:#FFF!important;}
```

bstable invocation:
```javascript
classes:"table,table-condensed,borderlessTable",
```
and borderlessTable was also hand-applied to each column:
```javascript
class:"borderlessTable",
```

This 99% works.  If anyone knows how to get rid of that last border, I'd love it, but it'd be nice if that could be a table property in the future.

(And please don't say use a row formatter; I have enough of those already.)
