### ISSUE TITLE
CSS thead-dark Class missing

### ISSUE THREAD

**Issue by e-medeiros** [wenzhixin/bootstrap-table#6867]
### Bootstraptable version(s) affected

1.22.0

### Description

tested with bootstrap 5

for some reason the style rule was removed... and its not black anymore :(

### Example(s)

even the editor online doesn't work.

https://live.bootstrap-table.com/example/options/thead-classes.html

### Possible Solutions

add CSS back ??? or revert the commit that remove the style...???
```css
.table .thead-dark th {
    background-color: #212529;
    border-color: #383f45;
    color: #fff;
}
```
