### ISSUE TITLE
Column Text Alignment in Print Extension 

### ISSUE THREAD

**Issue by wahono77** [wenzhixin/bootstrap-table#7093]
### Description

How to set column text alignment when printing is depend on column alignment in display? Currently all columns is centered text

**Comment by wenzhixin** [comment]
You can use the `printPageBuilderDefault` option to customize your style.
https://live.bootstrap-table.com/code/wenzhixin/16731
```css
th, td {
  text-align: left;
  vertical-align: middle;
}
```
