### ISSUE TITLE
Card View Issue in sub 350 px width

### ISSUE THREAD

**Issue by swayams** [wenzhixin/bootstrap-table#925]
The columns distort sub 350px how do I resolve it so that they show uniformly. Am I doing something wrong?

![card issue](https://cloud.githubusercontent.com/assets/11867582/7817929/031a1eac-03f6-11e5-82f0-92bbf577fc24.PNG)

**Comment by djhvscf** [comment]
Provide a fiddle please

**Comment by swayams** [comment]
https://jsfiddle.net/2bqxjc3c/ -  This holds up better thean the above implementations, but i would like to have a better gui all the same.

**Comment by wenzhixin** [comment]
Hi @swayams , I think you can custom the css style of card view title for your project:
```css
.fixed-table-body .card-view .title {
  font-weight: bold;
  display: inline-block;
  min-width: 30%;
  text-align: left !important;
}
```
